AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: TripSage AWS resources

Parameters:
  ResourceEnv:
    Description: 'Environment which the resources will be deployed to'
    Type: 'String'
    AllowedValues:
      - 'dev'
      - 'prod'

Conditions:
  IsProd: !Equals [!Ref ResourceEnv, 'prod']
  IsDev: !Equals [!Ref ResourceEnv, 'dev']

Resources:
###############
#  DynamoDb  #
###############
  TripSageDdbTableDev:
    Type: AWS::DynamoDB::Table
    Condition: IsDev
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: TripSage-Dev
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1_PK
          AttributeType: S
        - AttributeName: GSI1_SK
          AttributeType: S
        - AttributeName: GSI2_PK
          AttributeType: S
        - AttributeName: GSI2_SK
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1_PK
              KeyType: HASH
            - AttributeName: GSI1_SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2_PK
              KeyType: HASH
            - AttributeName: GSI2_SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  TripSageDdbTableProd:
    Type: AWS::DynamoDB::Table
    Condition: IsProd
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      TableName: TripSage-Prod
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1_PK
          AttributeType: S
        - AttributeName: GSI1_SK
          AttributeType: S
        - AttributeName: GSI2_PK
          AttributeType: S
        - AttributeName: GSI2_SK
          AttributeType: S
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1_PK
              KeyType: HASH
            - AttributeName: GSI1_SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: GSI2
          KeySchema:
            - AttributeName: GSI2_PK
              KeyType: HASH
            - AttributeName: GSI2_SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

#####################
#  Parameter Store  #
#####################

  TripSageDdbNameDev:
    Type: AWS::SSM::Parameter
    Condition: IsDev
    Properties:
      Description: Trip Sage DDB Name Dev
      Type: String
      Value: !GetAtt TripSageDdbTableDev.TableName

  TripSageDdbArnDev:
    Type: AWS::SSM::Parameter
    Condition: IsDev
    Properties:
      Description: Trip Sage DDB Arn Dev
      Type: String
      Value: !GetAtt TripSageDdbTableDev.Arn

  TripSageDdbNameProd:
    Type: AWS::SSM::Parameter
    Condition: IsProd
    Properties:
      Description: Trip Sage DDB Name Prod
      Type: String
      Value: !GetAtt TripSageDdbTableProd.TableName

  TripSageDdbArnProd:
    Type: AWS::SSM::Parameter
    Condition: IsProd
    Properties:
      Description: Trip Sage DDB Name Prod
      Type: String
      Value: !GetAtt TripSageDdbTableProd.Arn